--CREATE DATABASE SoftUni


CREATE TABLE Towns
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
Name NVARCHAR(100) NOT NULL
)

CREATE TABLE Addresses
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
AddressText NVARCHAR(250) NOT NULL,
TownId INT NOT NULL,
CONSTRAINT FK_Addresses_Towns FOREIGN KEY (TownId) REFERENCES Towns (Id)
)


CREATE TABLE Departments
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
Name NVARCHAR(100) NOT NULL
)

CREATE TABLE Employees
(
Id INT NOT NULL IDENTITY PRIMARY KEY,
FirstName NVARCHAR(100) NOT NULL,
MiddleName NVARCHAR(100),
LastName NVARCHAR(100) NOT NULL,
JobTitle NVARCHAR(100) NOT NULL,
DepartmentId INT NOT NULL,
CONSTRAINT FK_Employees_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments (Id),
HireDate DATE NOT NULL,
Salary MONEY NOT NULL,
AddressId INT NOT NULL,
CONSTRAINT FK_Employees_Addresses FOREIGN KEY (AddressId) REFERENCES Addresses (Id)
)

